[build]
  command = "pip install -t backend -r backend/requirements.txt"
  publish = "."
  functions = "backend"

[dev]
  command = "uvicorn backend.analyze:app --reload"
  publish = "."

[[redirects]]
  from = "/analyze"
  to = "/.netlify/functions/main/analyze"
  status = 200

[[redirects]]
  from = "/docs"
  to = "/.netlify/functions/main/docs"
  status = 200

[[redirects]]
  from = "/openapi.json"
  to = "/.netlify/functions/main/openapi.json"
  status = 200
